name: Release Pipeline

on:
  push:
    tags: ["v*"]
  workflow_dispatch:



jobs:
  quality-rust:
    uses: ./.github/workflows/_quality_rust.yml

  quality-python:
    uses: ./.github/workflows/_quality_python.yml

  test-matrix:
    needs: [quality-rust, quality-python]
    uses: ./.github/workflows/_test.yml
    with:
      cargo_profile: release

  build-release:
    needs: [test-matrix]
    uses: ./.github/workflows/_build.yml
    with:
      retention-days: 30

  publish:
    name: Create GitHub Release
    needs: [build-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@6d24a3e0f49f3e9a58d13a6f3260408422329883
        with:
          path: dist
          merge-multiple: true
      - uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: dist/*
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docs:
    needs: [test-matrix]
    uses: ./.github/workflows/_docs_build.yml

  deploy-docs:
    needs: [build-docs]
    uses: ./.github/workflows/_docs_deploy.yml

  publish-pypi:
    needs: [test-matrix]
    uses: ./.github/workflows/_publish_pypi.yml
